name: que_based_ecom_fe
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  dio: ^5.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  june: ^1.0.0+1
  percent_indicator: ^4.2.3
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_screen/splash.png"
  adaptive_icon_background: "#940f06"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#940f06"
  background_image: "assets/splash_screen/splash.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/splash_screen/
